# -*- coding: utf-8 -*-
"""Data Analysis Of NETFLIX Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UTM2YyQBi0XjbY8dJ9Ec7B5yPSUt4Z4D

# Data View

# Importing of the Dataset
"""

'''Importing the file for data analysis'''
import pandas as pd
df=pd.read_csv('/content/netflix_titles.csv')
df

'''Getting the description of the data'''
df.describe()

'''Getting the info of the data'''
df.info()

'''Getting the first 5 rows of the data'''
df.head()

'''Getting the last 5 rows of the data'''
df.tail()

"""#Total Count of the TV shows and Movies"""

'''Getting the count of TV Shows and movies'''
df.type.value_counts()

"""# Seperate the Information of the TV Shows"""

'''Getting the Info of the TV Shows'''
df1=df[df['type']=='TV Show']
df1

"""#Seperate the informtion of the Movies"""

'''Getting the Info of the Movies'''
df2=df[df['type']=='Movie']
df2

'''Getting the info of type and country'''
df3=df[['type','country']]
df3

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('type').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

'''Getting the info of the count of each country'''
df3 = df['country']
df3

"""# Network analysis of Actors / Directors and find interesting insights"""

'''Getting the info of the directors and cast'''
df4=df[['director','cast']]
df4

'''Getting the value counts of the Director andcast'''
df4.value_counts()

'''removing the null values'''
df4.dropna()

from matplotlib import pyplot as plt
_df_9['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

'''Getting the description of the cast'''
df4.describe()

'''Getting the info of the director'''
df5=df['director']
df5

'''Value  counts of the director'''
df5.value_counts()

"""# Understanding what content is available in different countries"""

'''getting the Understanding what content is available in different countries'''
df6=df[['country','listed_in']]
df6

from matplotlib import pyplot as plt
_df_3['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

'''Remove the null values'''
df6.dropna()

from matplotlib import pyplot as plt
_df_4['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

"""# Getting trends of tv shows and movies over time"""

'''Getting trends of tv shows and movies over time'''
df7=df[['type','release_year']]
df7

from matplotlib import pyplot as plt
import seaborn as sns
df7.groupby('type').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df7['release_year'].plot(kind='hist', bins=20, title='release_year')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
df7['release_year'].plot(kind='line', figsize=(8, 4), title='release_year')
plt.gca().spines[['top', 'right']].set_visible(False)



